name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  check:
    uses: ./.github/workflows/ci.yml
  release:
    needs: [check]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test
        run: pnpm test

      - name: Build
        run: pnpm build

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: |
          pnpm publish --no-git-checks --access public

      - name: Generate release notes
        run: changelogithub --output CHANGELOG.txt

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          body_path: CHANGELOG.txt
